### ISSUE TITLE
Your missing S in your alphabet

### ISSUE THREAD

**Issue by kjelle** [manifoldco/go-base32#3]
:)

**Comment by goughjt** [comment]
@kjelle The 's' is supposed to be missing. The 'i' and 'l' characters are also missing.
It is called "base32" because the "range" alphabet (that we map to) should have 32 characters.
```
// Package base32 implements unpadded base32 encoding, using our chosen
// alphabet.
```
In this package, the chosen 32-character alphabet is "0123456789abcdefghjkmnpqrtuvwxyz".
The authors intentionally left out 's', 'i' and 'l'.
I hope this is clear.
